name: dovehole
description: "The better way to contact, socialize, and share."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-76.0.dev

dependencies:
  flutter:
    sdk: flutter

  # I18n
  slang: ^4.7.1
  slang_flutter: ^4.7.0

  # BLoC Framework
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0 # Queue
  bloc_test: ^10.0.0

  # for <Dove Engine>
  flutter_js: ^0.8.3 # JavaScript Runtime
  flame: ^1.28.1
  flame_bloc: ^1.12.12

  # Database
  drift: ^2.26.1

  # Audio
  just_audio: ^0.10.2
  just_waveform: ^0.0.7
  just_audio_background: ^0.0.1-beta.16
  just_audio_windows: ^0.2.2 # [Windows] Support
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1 # [Linux] Support

  # Video
  chewie: ^1.11.3 # Player
  video_player: ^2.9.5
  video_player_media_kit: ^1.0.6
  media_kit_libs_windows_video: ^1.0.11 # [Windows] Support

  # Editor
  flutter_quill: ^11.4.0
  flutter_quill_extensions: ^11.0.0

  # @Layout
  # <Router>
  go_router: ^15.1.1

  # @Natice
  # <File>
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  # <System>
  flutter_local_notifications: ^19.1.0 # Notification
  connectivity_plus: ^6.1.4 # Network Status
  flutter_callkit_incoming: ^2.5.2 # Callkit
  flutter_native_splash: ^2.4.6 # Splash Screen
  # <Camera>
  camera: ^0.11.1
  camera_windows: ^0.2.6+2 # [Windows] Support
  camera_macos: ^0.0.9 # [macOS] Support
  camera_linux: ^0.0.8 # [Linux] Support

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

  # I18n Generator
  slang_build_runner: ^4.7.0

  # Router Generator
  go_router_builder: ^2.9.0

  # Database Generator
  drift_dev: ^2.26.1

  # Application Icon
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true